[build]
  publish = "public"
  command = "curl -sL https://github.com/Keats/gutenberg/releases/download/v0.3.3/gutenberg-v0.3.3-x86_64-unknown-linux-gnu.tar.gz | tar zxvf - && /opt/build/repo/gutenberg build"

[context.deploy-preview]
  command = "curl -sL https://github.com/Keats/gutenberg/releases/download/v0.3.3/gutenberg-v0.3.3-x86_64-unknown-linux-gnu.tar.gz | tar zxvf - && /opt/build/repo/docs/gutenberg build"

