[build]
publish = "public"
command = "zola build"
environment = { ZOLA_VERSION = "0.17.1" }

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "zola build --base-url $DEPLOY_PRIME_URL"